databases:
  - name: postgres
    ipAllowList: []
    databaseName: project_management
    user: jayesh

services:
  - type: web
    name: project_management
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false